<?php
/*
=====================================================
File Name: footer.inc
Author: Damith Shanelka
Created: 2026
Last Modified: 2026
Purpose: Reusable footer include file displayed
         at the bottom of all website pages
=====================================================
*/
?>
    <!-- Footer - appears on every page, italic centred text per spec -->
    <footer>
        <p>Created by: Group Members &mdash; Jayasanka &mdash; Shanelka &mdash; Geenod &mdash; Tharusha </a></p>
        <p>Email Your Tutor: <a href="mailto:rhettiarachchi@swin.edu.au" class="footer-p-link">Rukmal Hettiarachchi</a></p>
        <p>&copy; 2026 Swinburne University of Technology. All rights reserved.</p>
    </footer>

</body>
</html>
